// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NextAuthSessionProvider from "./providers/SessionProvider"; // path ตามจริง

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSessionProvider>
          <main className="min-h-screen flex flex-col m-auto" style={{ maxWidth: '600px'}}>
            <div className="flex-1 md:p-8">{children}</div>
          </main>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
